import type { Metadata } from 'next';

import { NAVIGATION_ITEMS } from '@/lib/constants/navigation';
import { Exo_2, Orbitron } from 'next/font/google';

import ContactForm from '@/components/common/ContactForm/ContactForm';
import Footer from '@/components/common/Footer/Footer';
import Navbar from '@/components/common/Navbar/Navbar';

import './globals.css';

const orbitron = Orbitron({
	variable: '--font-orbitron',
	subsets: ['latin'],
});

const exo2 = Exo_2({
	variable: '--font-exo2',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Astrobit',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${orbitron.variable} ${exo2.variable} antialiased`}>
				<Navbar items={NAVIGATION_ITEMS} />
				{children}
				<ContactForm />
				<Footer />
			</body>
		</html>
	);
}
